import type { Metadata } from 'next';
import { Bricolage_Grotesque } from 'next/font/google';
import './globals.css';

import { ReactQueryProvider } from '@/components/ReactQueryProvider';
import NavigationButtons from '@/components/NavigationButtons';

const bricolage_grotesque = Bricolage_Grotesque({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Academic Module',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReactQueryProvider>
			<html lang='en'>
				<body className={`${bricolage_grotesque.className} antialiased`}>
					<NavigationButtons />

					{children}
				</body>
			</html>
		</ReactQueryProvider>
	);
}
